version: '3.8'

volumes:
  db-data:
  vendor:
  var:

services:
  db:
    container_name: dokobit_db
    image: mysql:5.7
    restart: always
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootPassword
      MYSQL_DATABASE: dokobit
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  php:
    container_name: dokobit_php
    build:
      context: ./
      dockerfile: build/docker/Dockerfile
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    links:
      - db

  nginx:
    container_name: dokobit_nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www/html
      - ./build/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    links:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: dokobit_phpmyadmin
    depends_on:
      - db
    environment:
      UPLOAD_LIMIT: 2048M
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootPassword
    restart: always
    ports:
      - '8081:80'
